kind: Deployment
apiVersion: apps/v1
metadata:
   name: devopsdemo
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: devopsdemo
   template:
      metadata:
        labels:
          app: devopsdemo
      spec:
       containers:
        - name: devopsdemo
          image: crisnap/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 8000