kind: Service                             
apiVersion: v1
metadata:
  name: devopsdemo
  labels:
    app: devopsdemo
spec:
  ports:
    - port: 8080                               
      targetPort: 8000                  
      nodePort: 31200
  selector:
    app: devopsdemo                    
  type: LoadBalancer                   